### ISSUE TITLE
Is there a way to change the favicon?

### ISSUE THREAD

**Issue by jarodise** [verfasor/minimal-notion-blog#1]
Hi, thanks for creating the tutorial, I've followed it through and made my website already. 

However I find that favicon did not update along with Notion, can you tell me how I can set my own favicon? Thanks!

**Comment by verfasor** [comment]
Sorry for the delay. You should replace these icons in the public folder with yours:

https://github.com/jotzilla/minimal-notion-blog/tree/main/public
